#!/bin/bash

#Submit this script with: sbatch filename

#SBATCH --time=15:03:00   # walltime
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=256   # number of tasks per node
#SBATCH --job-name=HfTe5   # job name
#SBATCH --partition=standard   # partition name
#SBATCH --no-requeue   # do not requeue when preempted and on node failure
#SBATCH --signal=30@20  # send signal to job at [seconds] before end

module swap PrgEnv-cray PrgEnv-intel
module load cmake
module load cray-fftw
module load cray-hdf5/1.12.2.3


srun -n 256   /users/rkarkee/q-e-qe-7.3/bin/pw.x -pd .true.    < scf.in &> scf.out
